services:
  keep-frontend-common:
    ports:
      - "3010:3000"
    env_file:
      - .env
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - POSTHOG_KEY=${POSTHOG_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
      - PUSHER_HOST=${PUSHER_HOST}
      - PUSHER_PORT=${PUSHER_PORT}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}

  keep-backend-common:
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PUSHER_APP_ID=1
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=${PUSHER_HOST}
      - PUSHER_PORT=${PUSHER_PORT}
      - USE_NGROK=false

  keep-websocket-server-common:
    image: quay.io/soketi/soketi:1.4-16-debian
    ports:
      - "6010:6001"
      - "9601:9601"
    env_file:
      - .env
    environment:
      - SOKETI_USER_AUTHENTICATION_TIMEOUT=3000
      - SOKETI_DEBUG=1
      - SOKETI_DEFAULT_APP_ID=1
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
