version: "3.8"

services:
  keep-frontend-common:
    ports:
      - "3010:3000"
    environment:
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://s4ws84ossg00w4csk0o4w884.subbiesupport.net
      - NEXT_PUBLIC_API_URL=http://keep-backend:8080
      - POSTHOG_KEY=phc_muk9qE3TfZsX3SZ9XxX52kCGJBclrjhkP9JxAQcm1PZ
      - POSTHOG_HOST=https://ingest.keephq.dev
      - NEXT_PUBLIC_SENTRY_DSN=https://0d4d59e3105ffe8afa27dcb95a222009@o4505515398922240.ingest.us.sentry.io/4508258058764288
      - PUSHER_HOST=localhost
      - PUSHER_PORT=6010
      - PUSHER_APP_KEY=keepappkey

  keep-backend-common:
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=postgresql+psycopg2://keepadmin:keeppassword@local-postgres:5432/keep-db
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PUSHER_APP_ID=1
      - PUSHER_APP_KEY=keepappkey
      - PUSHER_APP_SECRET=keepappsecret
      - PUSHER_HOST=keep-websocket-server
      - PUSHER_PORT=6010
      - USE_NGROK=false

  keep-websocket-server-common:
    image: quay.io/soketi/soketi:1.4-16-debian
    ports:
      - "6010:6001"
      - "9601:9601"
    environment:
      - SOKETI_USER_AUTHENTICATION_TIMEOUT=3000
      - SOKETI_DEBUG=1
      - SOKETI_DEFAULT_APP_ID=1
      - SOKETI_DEFAULT_APP_KEY=keepappkey
      - SOKETI_DEFAULT_APP_SECRET=keepappsecret

  local-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: keepadmin
      POSTGRES_PASSWORD: keeppassword
      POSTGRES_DB: keep-db
    volumes:
      - keep_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keepadmin -d keep-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  keep_pgdata:
